### ISSUE TITLE
Uhensigtsmæssig eksponering af Clever credentials

### ISSUE THREAD

**Issue by kristofferandreasen** [fars-fede-fire/CleverAPI#1]
Hej @fars-fede-fire !

Jeg skriver på vegne af Clever A/S omkring dit repository her, som eksponerer credentials til offentligheden.
Vores API er ikke ment til at bruge brugt, hvis vi ikke eksplicit har givet tilladelse til det.

Vi ser derfor gerne, at disse authorization credentials ikke bliver eksponeret.
Du må meget gerne kontakte mig på kan@clever.dk med eventuelle spørgsmål.

**Comment by fars-fede-fire** [comment]
Hej @kristofferandreasen 
Selvfølgelig sletter jeg det, hvis I ønsker det.

Håber dog I vil åbne op for API i fremtiden. Jeg har skrevet en tilføjelse til Home Assistant (https://www.home-assistant.io/), som er et open source smart home system.
Her har jeg skrevet med flere folk der har brugt integrationen til at lade når der var overskud fra eget solcelle anlæg eller automatisk starter Clevers Intelligente opladning når stikket sættes i og læser fra bilen hvor mange % strøm bilen har behov for, så man slipper for at gøre dette manuelt via Clevers app, som jeg helt ærlig, aldrig får gjort, så er det nemmere at sætte antal kWh alt for højt...
Hvis ønsker det, sletter jeg selvfølgelig også Home Assistant tilføjelsen.

Men håber som sagt I vil åbne for et API i fremtiden.
Skriv gerne når I gør det, så hjælper jeg gerne med at lave en tilføjelse til Home Assistant!

Mvh

**Comment by kristofferandreasen** [comment]
Hej @fars-fede-fire 

Først og fremmest mange tak for din samarbejdsvillighed.
På nuværende tidspunkt ser vi gerne, at credentials her i repo slettes og at Home Assistant tilføjelsen fjernes.

Det er fedt at se, at du har bygget noget baseret på din egen use-case.
Jeg har sendt din feedback til vores produktejer af intelligent opladning, som også kigger på det.

I forhold til et åbent API har det været oppe og vende hos os i Clever IT, da vi gerne vil understøtte, at kunder selv kan interagere med deres boks. Dette er dog ikke planlagt i vores roadmap på nuværende tidspunkt, så jeg kan ikke sige noget om hvorvidt det kommer. 
Vi vil dog rigtig gerne række ud til dig, hvis det kommer.
Så kan vi få bygget en ny integration til Home Assistant til den tid.

**Comment by jolsso** [comment]
Hej @kristofferandreasen 
Kunne man forestille sig, at I opsætter et møde mellem Jeres PM og @fars-fede-fire for at få alt det viden bragt i spil som er genereret og få belyst de kundebehov, som dette løser. Det kunne være en fed måde at imødekomme, at godt arbejde ellers bliver slettet.

**Comment by bend0006** [comment]
Hej @kristofferandreasen 

Det er rigtig skidt, at I tvinger @fars-fede-fire til at lukke for sin tilføjelse.

Når man har smarte devices i sit hjem, forventer man at kunne kommunikere med dem.

Åbent API skal i roadmap nu!

**Comment by skandshus** [comment]
@kristofferandreasen i griber vel forhåbentlig denne her håndsrækning når der allerede ligger et kæmpe gratis arbejde på forhånd? Clever kan vel ikke ignorere det arbejde der ligger her fornuftigt set.. 
det ku jo være creater her ku lave det for jer med intern verificering efterfølgende? Det er win win for alle parter. Medmindre clevers grønne smarte ideer kun går til grænsen hvor de selv kan kapitalisere på det?:)

**Comment by madsdyd** [comment]
@kristofferandreasen Tak! Din henvendelse og jeres håndtering (herunder prioritering af åbne API'er) er præcist det der skulle til for endeligt at beslutte at jeg vil opsige mine to abbonementer hos jer. Vi har sågar købt og installeret to af jeres standere (altså dem som ladeboksene hænger på). Min kone og jeg har ellers været kunde hos jer siden 2019, men fadæsen med variable priser og nu dette ... Jeg har endda overtalt min arbejdsplads til at installere først to standere, senere 10 yderligere, men jeg kan altså ikke anbefale jer længere.

God vind til jer. I får sgu nok brug for det.

Og husk: https://en.wikipedia.org/wiki/Streisand_effect

**Comment by drhousedk2** [comment]
@kristofferandreasen Opførsel som denne bekræfter mig blot i mit valg om at forlade Clever i en pokkers til fart for et halvt års tid siden. Jeg har været kæmpe fortaler for Clever for 1+ år siden, men med den behandling kunderne fik samt nu denne understregelse af at Clever skal være lukket land forbeholdt dem der ikke forholder sig kritisk eller ønsker sig en "clever" løsning gør, at jeg aldrig kommer til at pege i retning af Clever igen.

**Comment by dgc-dev** [comment]
@kristofferandreasen Jeg kan kun tilslutte mig gruppen som meget gerne så åbne API'er på jeres roadmap ASAP.

**Comment by Jussi73** [comment]
I er jo helt væk. Et selskab som den grad markedsfører sig som bannerfører for den grønne omstilling har selvfølgelig et offentligt tilgængeligt API som tillader at lave integrationer med home assistant og andre styrings-applikationer, således at overskuddet i solanlæg kan kanaliseres over i laderen. At det ikke en gang er i jeres roadmap viser at grøn omstilling vist kun er noget I taler om i jeres markedsføring, og ikke er noget I rent faktisk mener. Godt man ikke er kunde hos jer mere....

**Comment by pkhacs** [comment]
Clever -- ;

**Comment by HansPeterHaastrup** [comment]
> Det er fedt at se, at du har bygget noget baseret på din egen use-case. 

Som ser ud til at være en forholdvis generel use-case.

Lige nu er det måske ikke så relevant - men hjemmeautomation er meget fremadgående. der er et til stadighed voksende kundesegment der vil automatisere - det er så lavthængende en frugt for Clever at give 'nørderne' adgang. Hvem er det som hr. og fru danmark spørger om hjælp til at vælge deres næste lader? Nørderne. Og når de ikke længere foreslår clever som førstevalg, så kan man nok se skriften på væggen.

**Comment by NickyM** [comment]
Så blev det alligevel ikke en Clever ladestander vi skulle have op og hænge.

**Comment by Idskov** [comment]
Jeg er helt vild med ironien i at et firma der hedder Clever, ikke prioriterer integration til Smarthome.
Forslag til nyt slogan: "We may be Clever, but we're not Smart"

Men i kan måske stadig nå at gribe den og vende det til noget positivt @kristofferandreasen

**Comment by sjskov** [comment]
Jeg kan kun opfordre Clever til at åbne for muligheden for API kald. Åbenhed og integration går hånd i hånd med brugertilfredshed. Giv os nu den frihed, vi alle gerne vil have gennem vores styrings-programmer - en frihed, som sikre en minimal belastning af elnettet og optimal udnyttelse af den grønne energi.

**Comment by VaabenDK** [comment]
Når jeg om et stykke tid skifter til en el-bis og får brug for ladestander, bliver et af mine vigtige kriterier at der er et API og Home assistant integration - ligesom jeg netop har gjort med min nye vaskemaskine (Bosch)
Så hvis Clever ikke er smart til den tid, bliver det noget andet

**Comment by nvanggaard** [comment]
@kristofferandreasen jeg vil godt tilslutte mig den efterhånden brede skare af utilfredse kunder.
Et åbent api er ikke raketvidenskab at udvikle, og hvorfor ikke slå sig op på at være ladeløsning en der integrerer med home Assistant, SmartThings, homey etc, i stedet for at leve i lukket land. Hvad er i bange for at miste?
I bliver ikke engang bedt om at lave integrationen til home Assistant, alt vi ønsker er et åbent api og en smule dokumentationen hertil

**Comment by Hoekeren** [comment]
@kristofferandreasen, lige som nogle softwarefirmaer præmierer folk der finder fejl og sårbarhed er i deres produkter, burde der være en tilskyndelse til dem der lægger tid og ressourcer i at bruge deres kompetencer at udvikle ekstra funktionalitet til jeres produkter til gavn for en stor og voksende gruppe mennesker, der efterspørger løsninger som I (endnu) ikke selv har afdækket. 
Som flere andre i tråden og skriver, så vil det ligge lige for at tage imod det udviklede og implementere det hurtigt som en del af jeres egen service. Det er en kæmpe besparelse for jer og vil give mange en længe efterspurgt åbenhed.

**Comment by LizardWizardGB** [comment]
@kristofferandreasen, det er ret uheldigt, da jeg netop lige havde besluttet at købe en Clever lader fordi jeg kunne integrere den i mit smarthome. Det er så ikke tilfældet mere og I har ikke engang tænkt jer at udvikle noget tilsvarende…

**Comment by mortenmoulder** [comment]
Hej @kristofferandreasen - dette var sidste dråbe for mig. Det sidste der holdte mig som kunde hos Clever, har været denne integration. Jeg vil håbe, I genovervejer dette træk, for ellers mistænker jeg at I kommer til at miste mange kunder - inklusiv mig. Jeg kommer til at følge med her og på jeres sociale medier. Jeg giver jer indtil juli til at offentliggøre hvad I har tænkt jer, og hører vi ikke noget, må vi antage I holder kortene tæt og har lyst til at miste kunder.

**Comment by JesperDonnis** [comment]
> 

Det her er en fantastisk use-case for hvorfor jeg IKKE skal vælge Clever som leverandør til min næste lader til sommerhuset. Jeg håber i lige vil tage et skridt tilbage og genoverveje beslutningen.

**Comment by AndersRasmussen** [comment]
Endnu en stemme for åbent API og embrace communitiet som gør jeres produkt endnu bedre end hvad I selv formår.
Håber I ombestemmer jer!

**Comment by klausdm** [comment]
Suk! Bare suk.

**Comment by jires** [comment]
Så er mine overvejelser om valg af ny leverandør til vores fælles projekter om ladestandere blevet meget nemmere... IKKE clever!!

**Comment by oli-dj** [comment]
Skuffende. Næsten ligeså skuffende som da jeg fik at vide at abonnement selvfølgelig ikke kunne sættets i bero mens elbilen var hos mekaniker i over halvanden måned.

**Comment by WantedLange** [comment]
Hvilken skam Clever - I taber kunderne på gulvet med dette.

**Comment by cweinberger** [comment]
> Jeg er helt vild med ironien i at et firma der hedder Clever, ikke prioriterer integration til Smarthome.
> 
> Forslag til nyt slogan: "We may be Clever, but we're not Smart"
> 
> 
> 
> Men i kan måske stadig nå at gribe den og vende det til noget positivt @kristofferandreasen

We are not Clever, but we're Smart. We at Monta will launch an official Public API for our users this month and a home assistant integration later in Q3.

See:

https://monta.upvoty.com/b/public-api/

**Comment by Daxziz** [comment]
> > Jeg er helt vild med ironien i at et firma der hedder Clever, ikke prioriterer integration til Smarthome.
> > Forslag til nyt slogan: "We may be Clever, but we're not Smart"
> > Men i kan måske stadig nå at gribe den og vende det til noget positivt @kristofferandreasen
> 
> We are not Clever, but we're Smart. We at Monta will launch an official Public API for our users this month and a home assistant integration later in Q3.
> 
> See:
> 
> https://monta.upvoty.com/b/app-features/public-api
> 
> https://monta.upvoty.com/b/app-features/home-assistant-integration

Stærkt! Det her gjorde lige at jeg komplet skiftede fokus på hvad jeg kiggede efter. Med opladning stort set kun hjemme, så er det vigtigeste for mig det forkromede overblik på hjemmefronten og kontrol af hvornår jeg kan lade billigst. Men jeg er nødt til at konkludere, at der er noget de ikke vil have jeg får chancen for at optimere (da det giver mindre økonomisk overskud til dem?), når et firma nægter at jeg selv kan tage kontrol og skal tvinges over i deres “intelligente opladning”. 

Monta gik fra at være noget jeg lige kunne kigge på ved lejlighed til at blive det mest spændende produkt nu og her.

Jeg fandt i hvert fald ud af at EnergiFyn med elaftale og en ladestander med Monta er et spændende alternativ at se nærmere på.

Mon ikke det her kunne blive et rigtig spændende emne for en af vores gode youtubere? 😃

**Comment by cweinberger** [comment]
@fars-fede-fire is there way to contact you? Email or LinkedIn?

**Comment by fars-fede-fire** [comment]
@cweinberger you can e-mail me at: jonas2204@hotmail.com.

**Comment by cweinberger** [comment]
As announced some weeks ago - here we are with our first version

## Monta Public API

We have *just* launched the first version of our 🧩 Public API to all our BETA users 🚀.

We can't wait to see what you are building with it! 🤩

You'll find the API docs and guides here: https://docs.public-api.monta.com

At Monta, we are deeply committed to empowering our end consumers by democratizing access to their data. We believe that you, as the users, should be in the driver's seat, steering your data in the way you desire. With the launch of our Public API, this mission is becoming a reality. 🤘🏻

## Monta Public API Hackathon

We are also hosting a hackathon at Monta and invite interested folks to join us and come up with great ideas.
More information + sign up form here: https://formcrafts.com/a/monta-hackathon

## What's next?
- More features on Public API
- Home Assistant plugin
- ...

**Comment by Daxziz** [comment]
Well done! That's a ton of work, but it's brilliant to see, that you're going in that direction. ASAP you'll have another customer :)

**Comment by kcadm** [comment]
> As announced some weeks ago - here we are with our first version
> 
> ## Monta Public API
> We have _just_ launched the first version of our 🧩 Public API to all our BETA users 🚀.
> 
> We can't wait to see what you are building with it! 🤩
> 
> You'll find the API docs and guides here: https://docs.public-api.monta.com
> 
> At Monta, we are deeply committed to empowering our end consumers by democratizing access to their data. We believe that you, as the users, should be in the driver's seat, steering your data in the way you desire. With the launch of our Public API, this mission is becoming a reality. 🤘🏻
> 
> ## Monta Public API Hackathon
> We are also hosting a hackathon at Monta and invite interested folks to join us and come up with great ideas. More information + sign up form here: https://formcrafts.com/a/monta-hackathon
> 
> ## What's next?
> * More features on Public API
> * Home Assistant plugin
> * ...

@cweinberger maybe you should also take a look at https://github.com/MTrab she had a cool integration going on for Clever's public charging network. Maybe there is also a good opportunity there for Monta. ;) Make it smart!

**Comment by smulle48** [comment]
Sjovt at der er larmende tavshed fra Clever 👍🤦🏻‍♂️

**Comment by Hoekeren** [comment]
> Sjovt at der er larmende tavshed fra Clever 👍🤦🏻‍♂️

Ja man får helt ondt i ørene

**Comment by sztypa** [comment]
Virker den slet ikke mere nu? Jeg har prøvet via HACS, men ved at skrive min mail ind, får jeg beskeden at den dur ikke...
"Unknown error occured" som de siger vest for Esbjerg.

**Comment by klausdm** [comment]
Nej. Det virker ikke mere.

**Comment by smulle48** [comment]
Jo det virker fint nok. Man skal bare selv finde indholdet til url filen :-)

**Comment by Hoekeren** [comment]
Så er spørgsmålet bare om man kender "nogen" der kan hjælpe med det?Med venlig hilsenChristian

**Comment by smulle48** [comment]
> Så er spørgsmålet bare om man kender "nogen" der kan hjælpe med det?Med venlig hilsenChristian

Du kan kontakte mig på Telegram. Jeg kender måske "nogen" der kan hjælpe :-)
[https://t.me/smulle48](https://t.me/smulle48)

**Comment by madsdyd** [comment]
Man kan også vælge at opsige sit abbonement. For real.

Eller bruge git ;-)

**Comment by smulle48** [comment]
> Man kan også vælge at opsige sit abbonement. For real.
> 
> Eller bruge git ;-)

mitmproxy fungere også glimrende til dette formål :-)

Man kan også bare backtracke i repo, så dukker det hele op :-D

**Comment by NicolaiPetri** [comment]
Øv øv øv. 
Har lige købt elbil og clever ville passe mig godt, men ikke uden integration room HA. 
Hvad har i andre valgt som alternativ ?

**Comment by smulle48** [comment]
> Øv øv øv. 
> Har lige købt elbil og clever ville passe mig godt, men ikke uden integration room HA. 
> Hvad har i andre valgt som alternativ ?

Fang mig på telegram 😄

**Comment by NicolaiPetri** [comment]
> > Øv øv øv. 
> > Har lige købt elbil og clever ville passe mig godt, men ikke uden integration room HA. 
> > Hvad har i andre valgt som alternativ ?
> 
> Fang mig på telegram 😄 

Hejsa. 
Hvis det bare er for at adgang til clevers api er det ikke interessant for mig. 
Jeg vil ikke bruge penge på en ladeløsning som måske lukker deres bagdør i morgen. 
Så jeg kigger på alternativer som E.ON, Looad og hvad der ellers er på markedet inden jeg overvejer Clever. 
Mvh. 
Nicolai

**Comment by smulle48** [comment]
> > > Øv øv øv. 
> > > Har lige købt elbil og clever ville passe mig godt, men ikke uden integration room HA. 
> > > Hvad har i andre valgt som alternativ ?
> > 
> > Fang mig på telegram 😄 
> 
> Hejsa. 
> Hvis det bare er for at adgang til clevers api er det ikke interessant for mig. 
> Jeg vil ikke bruge penge på en ladeløsning som måske lukker deres bagdør i morgen. 
> Så jeg kigger på alternativer som E.ON, Looad og hvad der ellers er på markedet inden jeg overvejer Clever. 
> Mvh. 
> Nicolai 
> 

Jeg har haft Clever siden oktober 2021 og de har ikke lukket det endnu 😄 

Godt jagt

**Comment by NicolaiPetri** [comment]
Det er en principsag. 😅
Og jeg kan se at f.eks. Looad understøtter at man har egen lader, så mon ikke man kan finde en der har åbent api.

**Comment by abandholm** [comment]
Hej @kristofferandreasen 

Nu er der gået et år. Er der noget nyt?

Jeres løsning mangler jo præcis at kunne få info fra bilen om hvad behovet er - og det kan man løse ved at kombinere bilens API med jeres. Det vil være uhyre nyttigt!

**Comment by xaviondk** [comment]
@fars-fede-fire kan det stadig bruges? Evt pm mig.

**Comment by smulle48** [comment]
> @fars-fede-fire kan det stadig bruges? Evt pm mig.

Nej desværre ikke

**Comment by xaviondk** [comment]
@smulle48 havde du en løsning? 🫢

**Comment by smulle48** [comment]
> @smulle48 havde du en løsning? 🫢

Jeg er ved at lægge hånd på de sidste finjusteringer efter de har ændret hele deres api godkendelse.

Skal bare lige have fundet en løsning der "nemt" kan bruges af alle

**Comment by Hoekeren** [comment]
Det kører fint hos mig :-) - når man bare lige har den rigtige url.py ;-)

**Comment by smulle48** [comment]
> Det kører fint hos mig :-) - når man bare lige har den rigtige url.py ;-)

Det gør det kun indtil du kommer til at logge ud eller bliver tvunget til at logge ind igen. Så hopper den over på det nye api

**Comment by Hoekeren** [comment]
Jeg har stadigt url.py liggende, så den bliver bare kopieret ind igen. Så plejer det at køre videre som før 🤗Med venlig hilsenChristianFra: smulle48 ***@***.***>Sendt: fredag, oktober 11, 2024 3:17:49 PMTil: fars-fede-fire/CleverAPI ***@***.***>Cc: Hoekeren ***@***.***>; Comment ***@***.***>Emne: Re: [fars-fede-fire/CleverAPI] Uhensigtsmæssig eksponering af Clever credentials (Issue #1)

Det kører fint hos mig :-) - når man bare lige har den rigtige url.py ;-)

Det gør det kun indtil du kommer til at logge eller bliver tvunget til at logge ind igen. Så hopper den over på det nye api

**Comment by resk10** [comment]
> > Det kører fint hos mig :-) - når man bare lige har den rigtige url.py ;-)
> 
> Det gør det kun indtil du kommer til at logge ud eller bliver tvunget til at logge ind igen. Så hopper den over på det nye api

Jeg får 'usernotfoundinwebshop' i loggen.
Det virker fint i app'en
Er det pga nyt api?

**Comment by smulle48** [comment]
> > > Det kører fint hos mig :-) - når man bare lige har den rigtige url.py ;-)
> 
> > 
> 
> > Det gør det kun indtil du kommer til at logge ud eller bliver tvunget til at logge ind igen. Så hopper den over på det nye api
> 
> 
> 
> Jeg får 'usernotfoundinwebshop' i loggen.
> 
> Det virker fint i app'en
> 
> Er det pga nyt api?

Det er min urls fil ;-)

Ved om de gradvist tvinger folk over på det nye api, men vil da lige stikke næsen i det igen :-)

**Comment by resk10** [comment]
Jeg er måske bare startet i det nye api, jeg er forholdsvis ny clever kunde.
For at få authentication til at virke er det da blot et spørgsmål om at rette i urls.py eller skal der også rettes kode?

**Comment by smulle48** [comment]
> Jeg er måske bare startet i det nye api, jeg er forholdsvis ny clever kunde.
> 
> For at få authentication til at virke er det da blot et spørgsmål om at rette i urls.py eller skal der også rettes kode?

De har flyttet hele deres godkendelse over til firebase, hvis jeg husker korrekt.

Så den nød skal jeg lige knække 😀 

Hvis man er forholdvis velbevandret i mitm, kan man godt selv finde api nøglerne, men det er nok lidt for nørdet til den almindelige bruger

**Comment by smulle48** [comment]
@xaviondk @resk10 Tjek min fork. Den skulle gerne virke nu med både gammelt og nyt api :-)

**Comment by klausdm** [comment]
> @xaviondk @resk10 Tjek min fork. Den skulle gerne virke nu med både gammelt og nyt api :-)

Hey Smulle
Har forsøgt, men får bare fejlmeddelse. Er det muligt du kan kontakte mig på mail: trouper_oysters_0y[at]icloud.com ?

**Comment by resk10** [comment]
@smulle48 - fedt, men er det rigtig gættet at det kræver at nogen af linjerne i urls.py opdateres? Den urls.py jeg har er en 'gammel' jeg har "fundet" et sted, og mitmproxy er nok lidt for avanceret for mig. 
Konkret tror jeg at jeg ser det samme som klausdm - når jeg har tastet min emailadresse får en jeg "unknown error". Jeg får rent faktisk en aktiveringsemail fra clever i min indbakke, men jeg kan ikke indsætte linket, da "unknow error" forhindrer at jeg fortsætter authentication flowet.

**Comment by jonirgens** [comment]
@smulle48 ja super fedt, men jeg får samme fejl "Unknown error occured" når jeg taster min email ind i første login billede "Send Clever authorization email". Jeg får dog ikke nogen aktiveringsemail fra clever, som resk10 gør.

**Comment by handswork** [comment]
Hi,
Jeg har fået det til at spille med de fleste ting, men mangler at få "SET_KWH" og "SET_DEPT_TIME" til at dukke op. tænker url'er ikke passer længere.
Jeg er med på Clever er lidt mærkelig omkring dette, men er der nogen som kan hjælpe mig videre?
tak

**Comment by torsaxtorff** [comment]
Hej alle.

Hvor langt er i med at få Clever integreret ?
Jeg kan se at i slut 2024 er der gang i tråden igen.

Nogen der evt. kan smide lidt billeder op, af deres dashboard med den del der virker med Clever pt.?

**Comment by Phimour** [comment]
> [@smulle48](https://github.com/smulle48) ja super fedt, men jeg får samme fejl "Unknown error occured" når jeg taster min email ind i første login billede "Send Clever authorization email". Jeg får dog ikke nogen aktiveringsemail fra clever, som resk10 gør.

Jeg får det samme :(

**Comment by allancph** [comment]
Hvor er det dårligt af clever. Hvilken ladestander skal vi så vælge for kunne bruge vores HA ?

**Comment by jonirgens** [comment]
> Hvor er det dårligt af clever. Hvilken ladestander skal vi så vælge for kunne bruge vores HA ?

Jeg har solpaneler, og da Clever ikke længere giver fradrag på forbrug på ladestandere når man har solpaneler har jeg droppet Clever. Det var dog en dyr omgang for mig, da jeg kun var kunde der i et år. På alle måder en dårlig og meget dyr oplevelse at være kunde hos Clever, og med super dårlig kundehåndtering og kunderådgivning.

Jeg har skiftet til Go-e ladere som har super integration ind i HA, samt skiftet til NRGi som stadig giver 50% refusion på afgiften ved billadning selv om man har sol paneler. NRGi tillader en lang liste af godkendte ladestandere. De fleste kendte ladestandere har en ok integration i HA (pånær Clever). Jeg valgte Go-e da de er billige, og mange anbefaler deres integration med HA - som jeg nu også er super glad for.

**Comment by WantedLange** [comment]
Kristoffer arbejder åbenbart ikke hos clever mere, så kan denne takedown jo være ligegyldig 😇😇

**Comment by smulle48** [comment]
> Kristoffer arbejder åbenbart ikke hos clever mere, så kan denne takedown jo være ligegyldig 😇😇

De har ændret det bagvedliggende api.

Jeg har alt info liggende, men er desværre ikke den skarpeste til Python. Jeg kan dog eksekvere de enkelte kommandoer direkte i cURL 😉

**Comment by VaabenDK** [comment]
Jeg er heller ikke den skarpeste til Python - men kan dog nogle ting. Måske du vil dele din info om det aktuelle api? Evt. i en DM?

**Comment by WantedLange** [comment]
> > Kristoffer arbejder åbenbart ikke hos clever mere, så kan denne takedown jo være ligegyldig 😇😇
> 
> De har ændret det bagvedliggende api.
> 
> Jeg har alt info liggende, men er desværre ikke den skarpeste til Python. Jeg kan dog eksekvere de enkelte kommandoer direkte i cURL 😉

Alt jeg ønsker, er blot at kunne rette afgangstid og lademængde - så hvis du kan dette via curl, så lytter jeg gerne øre :)

**Comment by smulle48** [comment]
> > > Kristoffer arbejder åbenbart ikke hos clever mere, så kan denne takedown jo være ligegyldig 😇😇
> > 
> > 
> > De har ændret det bagvedliggende api.
> > Jeg har alt info liggende, men er desværre ikke den skarpeste til Python. Jeg kan dog eksekvere de enkelte kommandoer direkte i cURL 😉
> 
> Alt jeg ønsker, er blot at kunne rette afgangstid og lademængde - så hvis du kan dette via curl, så lytter jeg gerne øre :)

Man kan ikke DM på GitHub, men smid mig en mail på smulle48@gmail.com så kan jeg nok hjælpe dig videre

**Comment by smulle48** [comment]
> Jeg er heller ikke den skarpeste til Python - men kan dog nogle ting. Måske du vil dele din info om det aktuelle api? Evt. i en DM?

Man kan ikke DM på GitHub, men smid mig en mail på smulle48@gmail.com så kan jeg nok hjælpe dig videre

**Comment by handswork** [comment]
Hvis der kunne komme liv i det igen ville jeg da være glad.
Er det muligt?

**Comment by smulle48** [comment]
> Hvis der kunne komme liv i det igen ville jeg da være glad.
> Er det muligt?

Jeg arbejder på at omskrive integrationen.

Indtil videre har jeg kørt det med cURL kald

**Comment by handswork** [comment]
Lyder lækkert! - glæder jeg mig til!

**Comment by torsaxtorff** [comment]
Det kunne være så lækkert med blot en lille smule adgang til Clever boksen i HA.
Føles som om jeg lever i stenalderen mht til min ladeboks 🥴😂

**Comment by Hoekeren** [comment]
JaTak det kunne være 😎 Med venlig hilsenChristian Skallerup-BørgesenFra: torsaxtorff ***@***.***>Sendt: lørdag, februar 7, 2026 8:59 PMTil: fars-fede-fire/CleverAPI ***@***.***>Cc: Hoekeren ***@***.***>; Comment ***@***.***>Emne: Re: [fars-fede-fire/CleverAPI] Uhensigtsmæssig eksponering af Clever credentials (Issue #1) torsaxtorff left a comment (fars-fede-fire/CleverAPI#1)Det kunne være så lækkert med blot en lille smule adgang til Clever boksen i HA.
Føles som om jeg lever i stenalderen mht til min ladeboks 🥴😂—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.
